source('https://rubygems.org')

gem('sinatra')
gem('sinatra-contrib', :require => "sinatra/reloader")
gem('rspec')
gem('capybara')
gem('launchy')
gem('pry')
gem('pg')
gem("sinatra-activerecord")
gem("rake")
